// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxkrigeblvxbrseloaqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4a3JpZ2VibHZ4YnJzZWxvYXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMDIyNTQsImV4cCI6MjA1OTY3ODI1NH0.9qQ1nNAklhNVEr89YdgYy76q4v3Z0L0uDOf3hQfr7ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);